#include<iostream>
using namespace std;
int main(){
    int x,y, sum ;
    cout<<"Enter first number:";
    cin>>x;
    cout<<"Enter second number:";
    cin>>y;
    sum=x+y;
    cout<<"Total no."<<sum<<endl;
}

// ------------------------------------------------------------------------------------

// Accept three no. form user and check which is larger no. 
// Accept radius of circle then find their area of circle 
// perfect no. 
// pallindrone no.
// armstrong no.
// robinson (krishnamurthy) (strong) number
// factorial number 