#include<iostream>
using namespace std ;

int main(){

   //  string s1 = "ROHIT" ;
   //  string s2="KUMAR" ;
   //  int len=s1.length();                                          // Length
   //  int len2=s2.length();
   //  cout<<len << " , "<<len2 ;

//  -----------------------------------------------------------------------------------

   //  string str = "HELLO WORLD";
   //  if(str.empty())  
   //  cout << "string is empty" ;
   //  else
   //  cout<< "string is not empty  \n" ;
   //  cout << "Length :" << str.length() << endl ;
   //  cout << "Substring: " << str.substr(0,4) << endl ;
   //  cout << "Find 'WORLD' :" << str.find("WORLD") << endl ;

   // ----------------------------------------------------------------------------------------------------

   //  str.replace(6,5 , "C++ ");
   //  cout<< "After Replace :" << str << endl ;

    // str.append("programming");                                      // str = str+"programming"
    // cout << "After append : "<<str << endl ;

// -------------------------------------------------------------------------------------------------    

   //   string str = "HELLOWORLD";
   //   str.erase (5,5);
   //   cout<<"str"<<endl ;

   //    string s="HELLO";
   //    s.insert(5,"WORLD");
   //    cout<< s<<endl ;

// -----------------------------------------------------------------------------------------------

   // string str= "HELLO WORLD";
   // cout<<str.at(3);              // str[3]
   // cout<<str.front();
   // cout<<str.back();
   // cout<<str.clear();

// ---------------------------------------------------------------------------------
   // string s2 ="computer";
   // sort(s2.begin(), s2.end());
   // cout<<s2 ;

// ----------------------------------------------------------------------------------
//   string s3 = "COMPUTER";
//   reverse(s3.begin(), s3.end());
//   cout<<s3 ;

// --------------------------------------------------------------------------------------
}